### ISSUE TITLE
VSTS CLI has been converted to a Azure CLI extension

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/Contribute#195]
As noted on [the repo](https://github.com/Microsoft/azure-devops-cli-extension) this is now an extension to the normal Azure CLI.
The language alias should probably be retired

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c11e26-0b4e-c922-1578-a487b16a7b7b
* Version Independent ID: 432d205a-c041-e6f7-0776-b13486fe2a1f
* Content: [How to use Markdown for writing Docs - Contributor Guide](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown)
* Content Source: [Contribute/how-to-write-use-markdown.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-use-markdown.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rloutlaw** [comment]
Corrected in the current version of the contributor guide linked to.

**Comment by nschonni** [comment]
Is that something that needs to get published from a private repo? Still seeing it in the repo and the live site

**Comment by nschonni** [comment]
Ah, looks like you changed this in your own fork https://github.com/rloutlaw/Contribute/pull/1/files

**Comment by JasonWHowell** [comment]
The change made it to master, but perhaps hasn't been merged to live. @BillWagner may know how to publish to live and the website. https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-use-markdown.md

**Comment by BillWagner** [comment]
Thanks for the ping @JasonWHowell I"ll open a PR to publish the live branch now.
